baseURL = "https://www.thesoilfactory.org"
languageCode = "en-us"
title = "The Soil Factory"
disableKinds = ["taxonomy"]
summaryLength = 30
enableRobotsTXT = "true"
assetDir = "/assets"
ignoreErrors = ["error-remote-getjson"]
[params]
  description = "Exploring Art, Science, and Sustainability"
  author = "WEAVE Community Inc."
  paypal = "https://www.paypal.com/donate/?hosted_button_id=7MRNCBDV37CCG"
  contact = "soilfactoryevents@gmail.com"
  handle = "thesoilfactory"
  subscribe = "https://groups.google.com/g/soil-factory-network"
  copyright = "WEAVE Community Inc."
  copyrighturl = "https://weavecommunity.org"
[assetDirs]
assets = "static"
[menus]
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 10
  [[menus.main]]
    name = 'Calendar'
    pageRef = '/calendar'
    weight = 20
  [[menus.main]]
    name = 'About Us'
    pageRef = '/about-us'
    weight = 30
  [[menus.main]]
    name = 'Contact Us'
    pageRef = '/contact-us'
    weight = 40
  [[menus.main]]
    name = 'Donors'
    pageRef = '/donors'
    weight = 50
  [[menus.main]]
    name = 'Movie Nights'
    pageRef = '/movie-nights'
    parent = 'Projects'
    weight = 10
  [[menus.main]]
    name = 'Multi-Disciplinary Meetings'
    pageRef = '/multi-disciplinary-meetings'
    parent = 'Projects'
    weight = 11
  [[menus.main]]
    name = 'Events'
    pageRef = '/events'
    parent = 'Projects'
    weight = 12
  [[menus.main]]
    name = 'Exhibitions'
    pageRef = '/exhibitions'
    parent = 'Projects'
    weight = 13
  [[menus.main]]
    name = 'Residencies'
    pageRef = '/residencies'
    parent = 'Projects'
    weight = 14
  [[menus.main]]
    name = 'The Marshy Garden'
    pageRef = '/the-marshy-garden'
    parent = 'Projects'
    weight = 15
  [[menus.main]]
    name = 'Art Share'
    pageRef = '/projects/art-share'
    parent = 'Projects'
    weight = 16
  [[menus.main]]
    name = 'Miyawaki Forest'
    pageRef = '/projects/miyawaki-forest'
    parent = 'Projects'
    weight = 17
  [[menus.main]]
    name = 'Calendar 2024'
    pageRef = '/calendar-2024'
    parent = 'Calendar'
    weight = 20
  [[menus.main]]
    name = 'Calendar 2023'
    pageRef = '/calendar-2023'
    parent = 'Calendar'
    weight = 21
  [[menus.main]]
    name = 'Calendar 2022'
    pageRef = '/calendar-2022'
    parent = 'Calendar'
    weight = 22